### PR TITLE
Mention pip packge in ReadMe

### PR DESCRIPTION
**Pull request by dschmitz89**
Hey there,

thanks for writing this wrapper for biteopt!

This PR simply adds information about the possibility to install biteopt via Pip. Of course, a label indicating that it is still experimental or something of that sort could be incorporated. 

As a side note: a recent [benchmark](http://infinity77.net/go_2021/thebenchmarks.html#results-aggregated-high-level-results) of derivative-free global optimizers in Python showed that biteopt is very competitive and outperforms scipy's global optimizers for certain types of problems such as complex curve fitting problems (NLSE benchmark). On the scipy mailing list this sparked interest in adding biteopt to scipy directly. Would you be interested in spearheading or supporting this?

### CODE REVIEW

**Comment by avaneev** [comment]
@dschmitz89 Just stumbled upon your post. It would be great to include biteopt there. However, the benchmark mentioned uses 2018 version of BiteOpt (I've discussed this with benchmark's author, but no results yet). The latest version (2021.27) is not yet widely benchmarked, but it's better in my benchmarks, maybe a little bit slower converging than 2018 version. Of course, not having benchmarks, harder to get confidence of a wider userbase. Worth a try anyway. Not counting convergence time (function evaluations), it's not too far to large-scale analytic optimizers like BARON at solving various medium-dimensinality problems; e.g. BiteOpt may solve 80% of problems in 20 attempts while BARON may solve 93% of problems; while BiteOpt needs no derivatives. These are just my estimations, needs independent assessment.

**Comment by avaneev** [comment]
@dschmitz89 I would also suggest exploring a possibility to implement constraint satisfaction as suggested on BiteOpt page: it's a quite effective approach. Since it's generally easy to implement it by hand, BiteOpt itself does not offer any constructs to support constraints satisfaction. If you are on Windows, you may check the `biteoptampl` which can solve NL models with constraints. The source code is included, so you may see how to implement standard constraints rules found in e.g. GAMS.

**Comment by dschmitz89** [comment]
Hey Alexey,

just saw your reply now.  I am convinced that biteopt is a powerful optimizer even with the older version from the benchmark. 

Regarding a possible scipy inclusion: this repo can serve as a very good starting point for a box constrained Biteopt port. Two things would be crucial to make this happen in my opinion.

First, two other return values are needed (see [scipy docs](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.OptimizeResult.html): the objective value after the optimization (which is already returned by the C++ code, easy) and the total number of function evaluations. Here I am not sure if I understand biteopt well enough: is it `iter*M*sqrt(m)*attc` ?

Second, currently functions which take numpy arrays as input do not work with this wrapper. I will try to look into this but am not much of a C person and numpy's C API looks a bit scary at first sight.

**Comment by avaneev** [comment]
The iteration budget is equal to `iter*sqrt(M)*attc` in `biteopt_minimize`.

**Comment by dschmitz89** [comment]
Was not aware that my updates would be pushed here directly, sorry for that. 

Regarding the discussion: I will soon release a version with numpy compability and scipy.optimize like API

**Pull request closed without merging**
